# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
r: bioc-release # Use bioconductor

sudo: false # Use containers

# Run Travis for pushes to the master branch only
branches:
  only:
   - master

r_packages:
  - covr
  - knitr

r_github_packages:
  - benja0x40/LittleThumb
  - benja0x40/QuickShift
  - benja0x40/Barbouille

warnings_are_errors: false

matrix:
  include:
    - os: linux
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes'
      env: R_CODECOV=true
    # - os: osx
    #   r_build_args: '--no-build-vignettes'
    #   r_check_args: '--ignore-vignettes'

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
