---
title: "BRD evaluation"
author: "Benjamin Leblanc"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{BRD evaluation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Helper functions

```{r, include=FALSE}
# =============================================================================.
#
# -----------------------------------------------------------------------------.
PlotRankedCorrelation <- function(
  x, inp = NULL, clrs, k = 256, q.p = c(0.25, 0.5, 0.75), ctr = 2,
  plot.dots = T, plot.iqr = T, plot.ctr = T, legend = T, ...
) {
  if(! is.null(inp)) x <- x - inp  
  xlim <- c(1, nrow(x))
  ylim <- range(x)
  y <- list()
  for(i in 1:ncol(x)) {
    y[[i]] <- runquantile(x[, i], k = k, probs = q.p)
  }
  names(y) <- colnames(x)
  plot(0, type = 'n', col = NA, xlim = xlim, ylim = ylim, ylab = "log2(counts)", ...)
  abline(h = 0, col = grey(0.5), lwd = 1)
  if(plot.dots) {
    for(i in ncol(x):1) {
      points(x[, i], pch = 20, cex = 0.3, col = ReplaceAlpha(clrs[i], 0.1))
    }
  }
  if(plot.iqr) {
    for(i in ncol(x):1) {
      segments(
        1:nrow(x), y[[i]][, 1], 1:nrow(x), y[[i]][, 3],
        col = ReplaceAlpha(clrs[i], 0.01)
      )
    }
  }
  if(plot.ctr) {
    for(i in ncol(x):1) {
      points(
        y[[i]][, ctr], type = 'l', lwd = 1.5, col = ReplaceAlpha(clrs[i], 0.9)
      )
    }
  }
  if(legend) legend("topright", colnames(x), fill = clrs, bty = 'n', cex = 0.8)
}
# =============================================================================.
#
# -----------------------------------------------------------------------------.
ParallelDensity <- function(data, k = 100, spacing = 0.2, jitter = "unif") {
  nc <- ncol(data)
  nr <- nrow(data)
  if(jitter == "triangle") {
    j <- rtriangle(nc * nr, a = -1, b = 1, c = 0)
  } else {
    j <- runif(nc * nr, -1, 1)
  }
  j <- j * (1 - spacing) / 2
  x <- rep(1:nc, each = nr)
  r <- 100 * diff(range(data))
  m <- cbind(r * x + j, as.vector(data))
  m <- cbind(m, knn_density(m, k = k))
  m[, 1] <- x + j
  colnames(m) <- c("x", "y", "d")
  m
}
# =============================================================================.
#
# -----------------------------------------------------------------------------.
PlotParallelDensity <- function(x, k, clr = "ry", spacing = 0.2, grid = T, ...) {

  m <- ParallelDensity(x, k, spacing)
  nc <- ncol(x)
  
  lim <- xylim(m[, 1:2], spacing = c(0, 0))
  empty.plot(xlim = lim$x, ylim = lim$y, axes = F, ...)
  if(grid) grid(nx = 0, ny = NULL)
  axis(2)
  axis(1, at = 1:nc, labels = colnames(x), las = 2, tick = F)
  clr <- colorize(m[, 3], mode = "rank", col = clr)
  # clr <- transformColors(clr, S.range = 0.9)
  points(m, cex = 0.5, col = clr)
}
# =============================================================================.
# veeeryyy slooow
# -----------------------------------------------------------------------------.
Boxplot <- function(
  x, whiskers = c(0.05,0.25, 0.5,0.75,0.95), medpch = 21, medcex=1.3,
  ...
) {
  bp <- boxplot(x, plot = F)
  bp$stats <- sapply(x, FUN = quantile, probs = whiskers, na.rm = T)
  bxp(
    bp, outline = F, show.names = T, axes = F, xaxs = 'i',
    pars = list(
      medlty = 1, boxlty = 1, whisklty = 1, medlwd = 1,
      medpch = medpch, medcex = medcex
    ),
    ...
  )
  axis(2)
  grid(nx = NA, ny = NULL)
}
```

### Initializations

```{r, include=FALSE}
suppressPackageStartupMessages(library(triangle))
suppressPackageStartupMessages(library(Barbouille))
suppressPackageStartupMessages(library(Tightrope))
```

### Global settings

```{r, include=FALSE}
base_path <- "/media/benjamin/USB16GB/LT_WORKS/" # mistral
base_path <- "/Volumes/USB16GB/LT_WORKS/"        # iMac
clr_map    <- function(k) colorize(k , mode = "rank")
clr_map    <- function(k) colorize(k , mode = "01", col = "ry")
clr_map.wg <- function(k) {
  clr <-  c(
      grey(c(0.8, 0.2)), rgb(1, 0.4, 1), rgb(1, 0.9, 1), rgb(0.6, 0.3, 1), rgb(0.2, 0, 0.4)
  )
  colorize(k , mode = "01", col = clr)
}

jit  <- "unif"
smx  <- 9
# "TSS_ENS", "GN_ENS", "CGI_UCSC"
max.cgi.dist <- 30000
```

### Orlando_et_al

DMSO + EPZ cell mix experiments in human jurkat cells (peripheral blood cells)

```{r, echo=FALSE, fig.height=5, fig.width=6.5, message=FALSE}
# =============================================================================.
fs <- (2 / 9) * (5 + 24) # ~6.5
# =============================================================================.
#
# -----------------------------------------------------------------------------.
data_path <- paste0(base_path, "GSE60104_Orlando_et_al_2014/_RDATA_/")
# -----------------------------------------------------------------------------.
# mapped_spikein <- readRDS(paste0(data_path, "mapped_spikein.rdata"))
# -----------------------------------------------------------------------------.
Orlando_et_al.H3K79me2 <- readRDS(paste0(data_path, "GN_Orlando_et_al_H3K79me2_smobs.rdata"))
Orlando_et_al.H3K4me3  <- readRDS(paste0(data_path, "GN_Orlando_et_al_H3K4me3_smobs.rdata"))
# -----------------------------------------------------------------------------.
roi <- "CGI_UCSC"
# -----------------------------------------------------------------------------.
# layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 2, 1), pch = 20, cex.main = 0.9, cex.lab = 0.8, cex.axis = 0.8)

for(wks_name in c("Orlando_et_al.H3K79me2", "Orlando_et_al.H3K4me3")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  # crx <- match(colnames(cnt), mapped_spikein$lt_id)
  # crx <- mapped_spikein$mapped_dm6[crx]
  crx <- match(colnames(cnt), wks$ann$lt_id)
  crx <- wks$ann$Reads.aligning.to.Drosophila[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  ylim <- range(crx, brd)
  h <- ParallelHist2D(
    crx, nx = 400, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "spike-in", ylim = ylim
  )
  h <- ParallelHist2D(
    brd, nx = 400, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "BRD", ylim = ylim
  )
}
```

```{r, echo=FALSE, fig.height=5, fig.width=6, message=FALSE}
for(wks_name in c("Orlando_et_al.H3K79me2", "Orlando_et_al.H3K4me3")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  # crx <- match(colnames(cnt), mapped_spikein$lt_id)
  # crx <- mapped_spikein$mapped_dm6[crx]
  crx <- match(colnames(cnt), wks$ann$lt_id)
  crx <- wks$ann$Reads.aligning.to.Drosophila[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  if(wks_name == "Orlando_et_al.H3K79me2") xps <- c("H3K79me2_0_R1", "H3K79me2_0_R2")
  if(wks_name == "Orlando_et_al.H3K4me3")  xps <- c("H3K4me3_0_R1", "H3K4me3_0_R2")
  
  o <- order(rowMeans(ldc[, xps] - inp.brd), decreasing = T)
  
  # layout(matrix(1:4, 2, 2, byrow = T))
  xps <- which(grepl("R1$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "spike-in")

  xps <- which(grepl("R1$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "BRD")

  xps <- which(grepl("R2$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "spike-in")
  
  xps <- which(grepl("R2$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "BRD")
}
```

### ESC_BRD

SUZ12 WT + KO cell mix experiments in mouse ESCs.

```{r, echo=FALSE, fig.height=5, fig.width=6.5, message=FALSE}
# =============================================================================.
fs <- (2 / 9) * (5 + 24) # ~6.5
# =============================================================================.
#
# -----------------------------------------------------------------------------.
# fpath <- paste0(base_path, "NextSeq_ESC_BRD_R1_TEST/_RDATA_/mapped_spikein.RData")
# r1 <- readRDS(fpath)
# fpath <- paste0(base_path, "NextSeq_ESC_BRD_R2_TEST/_RDATA_/mapped_spikein.RData")
# r2 <- readRDS(fpath)
# fpath <- paste0(base_path, "NextSeq_ESC_BRD_RDATA/mapped_spikein.rdata")
# saveRDS(rbind(r1, r2), fpath)
# rm(r1, r2)
# =============================================================================.
data_path <- paste0(base_path, "NextSeq_ESC_BRD_RDATA/")
# -----------------------------------------------------------------------------.
mapped_spikein <- readRDS(paste0(data_path, "mapped_spikein.rdata"))
# -----------------------------------------------------------------------------.
ESC_BRD.H3K27me3 <- readRDS(paste0(data_path, "GN_ENS_ESC_BRD_H3K27me3_smobs.rdata"))
ESC_BRD.Suz12    <- readRDS(paste0(data_path, "CGI_UCSC_ESC_BRD_Suz12_smobs.rdata"))
# -----------------------------------------------------------------------------.
roi <- "CGI_UCSC"
# -----------------------------------------------------------------------------.
# layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 2, 1), pch = 20, cex.main = 0.9, cex.lab = 0.8, cex.axis = 0.8)

for(wks_name in c("ESC_BRD.H3K27me3", "ESC_BRD.Suz12")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- which(grepl("_0_", colnames(cnt)))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  ylim <- range(crx, brd)
  h <- ParallelHist2D(
    crx, nx = 400, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "spike-in", ylim = ylim
  )
  h <- ParallelHist2D(
    brd, nx = 400, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "BRD", ylim = ylim
  )
}
```

```{r, echo=FALSE, fig.height=5, fig.width=6, message=FALSE}
for(wks_name in c("ESC_BRD.H3K27me3", "ESC_BRD.Suz12")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- which(grepl("_0_", colnames(cnt)))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  if(wks_name == "ESC_BRD.H3K27me3") xps <- c("ESC_H3K27me3_100_R1", "ESC_H3K27me3_100_R2")
  if(wks_name == "ESC_BRD.Suz12")    xps <- c("ESC_Suz12_100_R1", "ESC_Suz12_100_R2")
  
  o <- order(rowMeans(ldc[, xps] - inp.brd), decreasing = T)
  
  # layout(matrix(1:4, 2, 2, byrow = T))
  xps <- which(grepl("R1$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "spike-in")

  xps <- which(grepl("R1$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "BRD")

  xps <- which(grepl("R2$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "spike-in")
  
  xps <- which(grepl("R2$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "BRD")
}
```

### NSC_K27M

H3WT versus K27M experiments in mouse NSCs.

```{r, echo=FALSE, fig.height=5, fig.width=6.5, message=FALSE}
# =============================================================================.
fs <- (2 / 9) * (5 + 24) # ~6.5
# =============================================================================.
#
# -----------------------------------------------------------------------------.
# fpath <- paste0(base_path, "NextSeq_ESC_BRD_R1_TEST/_RDATA_/mapped_spikein.RData")
# r1 <- readRDS(fpath)
# fpath <- paste0(base_path, "NextSeq_ESC_BRD_R2_TEST/_RDATA_/mapped_spikein.RData")
# r2 <- readRDS(fpath)
# fpath <- paste0(base_path, "NextSeq_ESC_BRD_RDATA/mapped_spikein.rdata")
# saveRDS(rbind(r1, r2), fpath)
# rm(r1, r2)
# =============================================================================.
data_path <- paste0(base_path, "NextSeq_K27M_spike_in/_RDATA_/")
# -----------------------------------------------------------------------------.
mapped_spikein <- readRDS(paste0(data_path, "mapped_spikein.rdata"))
# -----------------------------------------------------------------------------.
NSC_K27M.H3K27me3 <- readRDS(paste0(data_path, "GN_ENS_NSC_K27M_H3K27me3_smobs.rdata"))
# -----------------------------------------------------------------------------.
roi <- "CGI_UCSC"
# -----------------------------------------------------------------------------.
# layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 2, 1), pch = 20, cex.main = 0.9, cex.lab = 0.8, cex.axis = 0.8)

for(wks_name in c("NSC_K27M.H3K27me3")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  ylim <- range(crx, brd)
  h <- ParallelHist2D(
    crx, nx = 400, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "spike-in", ylim = ylim
  )
  h <- ParallelHist2D(
    brd, nx = 400, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "BRD", ylim = ylim
  )
}
```

```{r, echo=FALSE, fig.height=5, fig.width=6, message=FALSE}
for(wks_name in c("NSC_K27M.H3K27me3")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  xps <- c("H3WT_DMSO_H3K27me3_R1", "H3WT_DMSO_H3K27me3_R2")
  o <- order(rowMeans(ldc[, xps] - inp.brd), decreasing = T)
  
  xps <- which(grepl("R1$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "spike-in")

  xps <- which(grepl("R1$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "BRD")

  xps <- which(grepl("R2$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "spike-in")
  
  xps <- which(grepl("R2$", colnames(cnt)) & ! colnames(cnt) %in% wks$controls)
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = SuperRainbow(length(xps)), plot.dots = F, main = "BRD")
}
```

### E14_EPZ

EZH2 inhibitor washout experiments in mouse ESCs.

```{r, echo=FALSE, fig.height=5, fig.width=3, message=FALSE}
# =============================================================================.
fs <- (2 / 9) * (5 + 8) # ~3
# =============================================================================.
data_path <- paste0(base_path, "NextSeq_E14EPZ/_RDATA_/")
# -----------------------------------------------------------------------------.
ROI.LST <- readRDS(paste0(data_path, "ROI.LST.rdata"))
# -----------------------------------------------------------------------------.
mapped_spikein <- readRDS(paste0(data_path, "mapped_spikein.rdata"))
# -----------------------------------------------------------------------------.
E14_EPZ.me3   <- readRDS(paste0(data_path, "GN_ENS_E14_EPZ_H3K27me3_smobs.rdata"))
E14_EPZ.me2   <- readRDS(paste0(data_path, "CGI_UCSC_E14_EPZ_H3K27me2_smobs.rdata"))
E14_EPZ.me1   <- readRDS(paste0(data_path, "CGI_UCSC_E14_EPZ_H3K27me1_smobs.rdata"))
E14_EPZ.Suz12 <- readRDS(paste0(data_path, "CGI_UCSC_E14_EPZ_Suz12_smobs.rdata"))
# -----------------------------------------------------------------------------.
roi <- "CGI_UCSC"
# =============================================================================.
# layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 2, 1), pch = 20, cex.main = 0.9, cex.lab = 0.8, cex.axis = 0.8)
# -----------------------------------------------------------------------------.
for(wks_name in c("E14_EPZ.me3", "E14_EPZ.me2", "E14_EPZ.me1", "E14_EPZ.Suz12")) {

  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  # crx <- wks$ann$mapped.nbr.dm3
  names(crx) <- colnames(cnt)
  crx <- crx[1:8]
  crx <-  log2(mean(crx) / crx)
  inp.crx <- inp.ldc # PROBLEM HERE
  crx <- t(t(ldc[, 1:8]) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  ylim <- range(crx, brd)
  h <- ParallelHist2D(
    crx, nx = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "spike-in", ylim = ylim
  )
  h <- ParallelHist2D(
    brd[, 1:8], nx = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "BRD", ylim = ylim
  )
}
```

```{r, eval=FALSE, fig.height=5, fig.width=6, message=FALSE, include=FALSE}
for(wks_name in c("E14_EPZ.me3", "E14_EPZ.me2", "E14_EPZ.me1", "E14_EPZ.Suz12")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  if(wks_name == "E14_EPZ.me3") k27me3.chk <- chk
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  # crx <- wks$ann$mapped.nbr.dm3
  names(crx) <- colnames(cnt)
  crx <- crx[1:8]
  crx <-  log2(mean(crx) / crx)
  inp.crx <- inp.ldc # PROBLEM HERE
  crx <- t(t(ldc[, 1:8]) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  if(wks_name == "E14_EPZ.me3") {
    xps <- c("H3K27me3_E14", "H3K27me3_96h")
    k27me3.o <- order(rowMeans(ldc[, xps] - inp.brd), decreasing = T)
  }
  o <- k27me3.o[chk[k27me3.chk]]

  xps <- 1:8
  clrs <- c("black", rgb(0:6/6, 0, 6:0/6))
  PlotRankedCorrelation(x = crx[o, xps], inp = inp.crx[o], clrs = clrs, plot.dots = F, main = "spike-in")
  PlotRankedCorrelation(x = brd[o, xps], inp = inp.brd[o], clrs = clrs, plot.dots = F, main = "BRD")
}
```

```{r, eval=FALSE, fig.height=5, fig.width=6, message=FALSE, include=FALSE}
# =============================================================================.
fs <- (2 / 9) * (5 + 8) # ~3
# =============================================================================.
roi.grg <- ROI.LST$CGI_UCSC
wg.grg  <- ROI.LST$WHOLE_GENOME
# -----------------------------------------------------------------------------.
wg.dist <- c()
for(chr in seqlevels(wg.grg)) {
  wg.idx <- which(seqnames(wg.grg) == chr)
  x.wg   <- (start(wg.grg[wg.idx]) + end(wg.grg[wg.idx])) / 2
  roi.idx <- which(seqnames(roi.grg) == chr)
  if(length(roi.idx) > 0) {
    x.roi   <- (start(roi.grg[roi.idx]) + end(roi.grg[roi.idx])) / 2
    wg.dist <- c(wg.dist, knnx.dist(query = x.wg, data = x.roi, k = 1))
  } else {
     wg.dist <- c(wg.dist, rep(Inf, length(wg.idx)))
  }
}

# =============================================================================.
# layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 2, 1), pch = 20, cex.main = 0.9, cex.lab = 0.8, cex.axis = 0.8)
# -----------------------------------------------------------------------------.
for(wks_name in c("E14_EPZ.me3", "E14_EPZ.me2", "E14_EPZ.me1", "E14_EPZ.Suz12")) {
  
  message(wks_name)
  wks <- get(wks_name)

  wg.cnt <- wks$CNT$WHOLE_GENOME
  chk <- wg.dist < max.cgi.dist & FiniteValues(log2(wg.cnt))
  wg.inp <- wg.cnt[chk, wks$controls]
  wg.cnt <- wg.cnt[chk, 1:8]

  wg.ldc <- log2(DitherCounts(wg.cnt))
  wg.ldc <- t(t(wg.ldc) + wks$BRD$normfactors[1:8])
  
  wg.inp <- log2(DitherCounts(wg.inp))
  wg.inp <- t(t(wg.inp) + wks$BRD$normfactors[wks$controls])
  wg.inp <- rowMeans(wg.inp)
  
  # wg.ldc <- wg.ldc - log2(DitherCounts(wg.inp) * 2^wks$BRD$normfactors[9])
  wg.ldc <- wg.ldc - wg.inp
  
  # layout(matrix(1:9, 3, 3, byrow = T))
  ylim <- range(wg.ldc)
  for(i in 1:ncol(wg.ldc)) {
    h <- Histogram2D(
      x = wg.dist[chk], y = wg.ldc[, i], nx = 150, ny = 150,
      plot = T, ylim = ylim, clrmap = clr_map.wg,
      xlab = "distance to CGI (bp)", ylab = "log2(counts / input)",
      main = colnames(wg.ldc)[i]
    )
    abline(h = 0, col = rgb(1, 0.8, 0), lwd = 1.5)
  }
  empty.plot(axes = F)
}
```

### Lu_et_al

H3WT versus K36M experiments from Lu et al., 2016.


<!-- s = b (4 + 1 + a nc) -->
<!-- b = 2 / (4 + 1 + 4) -->
<!-- a = (2 - 10 / 9) * 9 / 8 -->

```{r, echo=FALSE, fig.height=5, fig.width=2, message=FALSE}
# =============================================================================.
fs <- (2 / 9) * (5 + 4)
# =============================================================================.
data_path <- paste0(base_path, "GSE63195_Lu_et_al_2016/_RDATA_/")
# -----------------------------------------------------------------------------.
ROI.LST <- readRDS(paste0(data_path, "ROI.LST.rdata"))
# -----------------------------------------------------------------------------.
mapped_spikein <- readRDS(paste0(data_path, "mapped_spikein.rdata"))
# -----------------------------------------------------------------------------.
Lu_et_al.H3K36me3 <- readRDS(paste0(data_path, "GN_Lu_et_al_H3K36me3_smobs.rdata"))
Lu_et_al.H3K27me3 <- readRDS(paste0(data_path, "GN_Lu_et_al_H3K27me3_smobs.rdata"))
# -----------------------------------------------------------------------------.
roi <- "TSS_ENS"
# =============================================================================.
# layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 2, 1), pch = 20, cex.main = 0.9, cex.lab = 0.8, cex.axis = 0.8)
# -----------------------------------------------------------------------------.
for(wks_name in c("Lu_et_al.H3K36me3", "Lu_et_al.H3K27me3")) {
  
  message(wks_name)
  wks <- get(wks_name)
  
  cnt <- wks$CNT[[roi]]
  ctl <- match(wks$controls, colnames(cnt))
  chk <- FiniteValues(log2(cnt))
  inp.cnt <- cnt[chk, ctl]
  cnt <- cnt[chk, ]
  
  ldc <- log2(DitherCounts(cnt))
  inp.ldc <- log2(DitherCounts(inp.cnt))
  
  inp.brd <- t(t(inp.ldc) + wks$BRD$normfactors[ctl])
  brd <- t(t(ldc) + wks$BRD$normfactors)
  
  crx <- match(colnames(cnt), mapped_spikein$lt_id)
  crx <- mapped_spikein$mapped_dm6[crx]
  names(crx) <- colnames(cnt)
  crx <-  log2(mean(crx) / crx)
  inp.crx <- t(t(inp.ldc) + crx[ctl])
  crx <- t(t(ldc) + crx)

  inp.brd <- rowMeans(inp.brd)
  inp.crx <- rowMeans(inp.crx)

  ylim <- range(crx, brd)
  h <- ParallelHist2D(
    crx, nx = 100, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "spike-in", ylim = ylim
  )
  h <- ParallelHist2D(
    crx, nx = 100, ny = 200, plot = T, clrmap = clr_map, jitter = jit, smoothx = smx, 
    las = 2, ylab = "log2(counts)", main = "BRD", ylim = ylim
  )
}
```














```{r, eval=FALSE, include=FALSE}

cgi.me3 <- E14_EPZ.me3$CNT$CGI_UCSC
cgi.me2 <- E14_EPZ.me2$CNT$CGI_UCSC
cgi.me1 <- E14_EPZ.me1$CNT$CGI_UCSC

chk <- FiniteValues(log2(cbind(cgi.me3, cgi.me2, cgi.me1)))

cgi.me3 <- cgi.me3[chk, ]
cgi.me2 <- cgi.me2[chk, ]
cgi.me1 <- cgi.me1[chk, ]

cgi.me3 <- log2(DitherCounts(cgi.me3)) 
cgi.me2 <- log2(DitherCounts(cgi.me2)) 
cgi.me1 <- log2(DitherCounts(cgi.me1)) 

cgi.me3 <- t(t(cgi.me3) + E14_EPZ.me3$BRD$scaling)
cgi.me2 <- t(t(cgi.me2) + E14_EPZ.me2$BRD$scaling)
cgi.me1 <- t(t(cgi.me1) + E14_EPZ.me1$BRD$scaling)


o <- order(rowMeans(cgi.me3[, c(1, 8)]), decreasing = T)

cgi.me3 <- cgi.me3[o, ]
cgi.me2 <- cgi.me2[o, ]
cgi.me1 <- cgi.me1[o, ]

n <- ncol(cgi.me3) - 2
clr <- c("black", rgb(0:n/n, 0.5*n:0/n, n:0/n))

nc <- ncol(cgi.me3)
nr <- nrow(cgi.me3)


layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(10, 4, 3, 1), pch = 20, cex.lab = 0.9, cex.axis = 0.9)

boxplot(cgi.me3, las = 2, main = "H3K27me3")
abline(h = median(cgi.me3[, 1]))
boxplot(cgi.me2, las = 2, main = "H3K27me2")
abline(h = median(cgi.me2[, 1]))
boxplot(cgi.me1, las = 2, main = "H3K27me1")
abline(h = median(cgi.me1[, 1]))

par(mar = c(5, 4, 3, 1), pch = 20, cex.lab = 0.9, cex.axis = 0.9)

empty.plot(xlim = c(1, nr), ylim = range(cgi.me3))
for(i in 1:nc) points(runmed(cgi.me3[, i], 255), type = "l", col = clr[i])

empty.plot(xlim = c(1, nr), ylim = range(cgi.me2))
for(i in 1:nc) points(runmed(cgi.me2[, i], 255), type = "l", col = clr[i])

empty.plot(xlim = c(1, nr), ylim = range(cgi.me1))
for(i in 1:nc) points(runmed(cgi.me1[, i], 255), type = "l", col = clr[i])

x <- rep(1:nc, each = nr)
x <- x + runif(nc * nr, -1, 1) / 2 # (2 * x + DitherCounts(x)) / 3
y <- rep(1:nr, nc)
y <- 10 * (y + DitherCounts(y)) / (2 * nr)


layout(matrix(1:9, 3, 3, byrow = T))
par(mar = c(5, 4, 3, 1), pch = 20, cex.lab = 0.9, cex.axis = 0.9)
empty.plot(xlim = 1:ncol(cgi.me3), )
plot(x = as.factor(colnames(cgi.me3)), y = rep(NA, ncol(cgi.me3)), type = "n", ylim = range(m[, 2]))

m <- mk_xyd(cgi.me3, k = 200)
plot(m, cex = 0.5, col = colorize(sqrt(m[, 3]), mode = "rank", col = "ry"))

m <- mk_xyd(cgi.me2, k = 200)
plot(m, cex = 0.5, col = colorize(sqrt(m[, 3]), mode = "rank", col = "ry"))

m <- mk_xyd(cgi.me1, k = 200)
plot(m, cex = 0.5, col = colorize(sqrt(m[, 3]), mode = "rank", col = "ry"))

# violin <- function(x, d) {
#   d <- d / max(d)
#   x <- x + d * runif(length(x), -1, 1) / 3
#   x
# }
# 
# x <- rep(1:nc, each = nr)
# 
# z <- as.vector(cgi.me3)
# d <- knn_density(z, k = 50)
# z <- cbind(violin(x, d), z)
# plot(z, cex = 0.5, col = colorize(sqrt(d), mode = "01", col = "ry"))


# library(rgl)

# z <- cbind(x, y, as.vector(cgi.me3))
# plot3d(z[, 1], z[, 2], z[, 3], col = grey(0.3), alpha = 0.1)
# z <- cbind(x, y, as.vector(cgi.me2))
# plot3d(z[, 1], z[, 2], z[, 3], col = grey(0.3), alpha = 0.1)
# z <- cbind(x, y, as.vector(cgi.me1))
# plot3d(z[, 1], z[, 2], z[, 3], col = grey(0.3), alpha = 0.1)


```

