---
title: "Multivariate density estimation"
author: "Benjamin Leblanc"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{density}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
suppressPackageStartupMessages(library(Tightrope))
```


```{r}
library(Tightrope)
```

Example with a patterned distribution of counts

```{r}
n_obs <- 100000
p <- rep(c(1, 1, 2, 3, 2, 1, 1), length.out = 14)
rs <- RandomCounts(n_obs, d = 2, p = p)
```

```{r}
x <- DitherCounts(rs$x)
p <- knn_density(x, k = 100)
```

```{r , fig.width=7.15, fig.height=2.65}
layout(matrix(1:3, 1, 3))
par(mar = c(5, 4, 3, 1), pch = 20, cex.lab = 1.0, cex.axis = 1.0)
h <- histogram2D(x, method = "ash", plot = T, main = "ash density")
plot_samples(x, clr = colorize(p), cex = 0.2, main = "knn density")
```

```{r}
n_obs <- 20000
rs <- SimulatedCounts(n_obs, poorcounts = list(mu = 1.5, sigma = 1.5))
```

```{r}
x <- log2(DitherCounts(rs$x))
p <- knn_density(x, k = 100)
```


```{r , fig.width=7.15, fig.height=2.65}
layout(matrix(1:3, 1, 3))
par(mar = c(5, 4, 3, 1), pch = 20, cex = 0.5, cex.lab = 1.0, cex.axis = 1.0)
plot_samples(x, idx = c(1, 2), clr = colorize(p, mode = "r"), main = "density")
```
