# =============================================================================.
#' Ensembl genes - Homo sapiens - GRCh38 / hg38 (rel. 91, Dec. 2017)
# -----------------------------------------------------------------------------.
#' @keywords internal
"EGA91_human"

# =============================================================================.
#' Ensembl genes - Mus musculus - GRCm38 / mm10 (rel. 91, Dec. 2017)
# -----------------------------------------------------------------------------.
#' @keywords internal
"EGA91_mouse"

# =============================================================================.
#' UCSC CGIs - Homo sapiens - GRCh38 / hg38
# -----------------------------------------------------------------------------.
#' @keywords internal
"CGI_hg38"

# =============================================================================.
#' UCSC CGIs - Mus musculus - GRCm38 / mm10
# -----------------------------------------------------------------------------.
#' @keywords internal
"CGI_mm10"

# =============================================================================.
#' ENCODE blacklist - Homo sapiens - GRCh38 / hg38
# -----------------------------------------------------------------------------.
#' @keywords internal
"hg38_blacklist"

# =============================================================================.
#' ENCODE blacklist - Mus musculus - GRCm38 / mm10
# -----------------------------------------------------------------------------.
#' @keywords internal
"mm10_blacklist"

# =============================================================================.
#' H3K27me3 ChIP-seq in mouse Neuronal Stem Cell (NSCs) - READ COUNTS
# -----------------------------------------------------------------------------.
#' @description
#' NSC_K27M_COUNTS: Precomputed read count matrixes (mm10)
#'
#' NSC_K27M_METADATA: Annotation of experimental conditions
#'
#' NSC_K27M_SPIKEIN: Number of Drosophila reads (spike-in)
#'
#' @details
#' This ChIP-seq dataset was generated by reproducing experiments presented
#' in our study about the role of the H3.3K27M histone mutation in DIPG
#' (Mohammad et al., 2017), but adding spike-in with Drosophila chromatin
#' in the ChIP-seq protocol.
#' Briefly, H3K27me3 ChIP-seq experiments were performed in mouse NSCs, in
#' presence or absence of expression of the H3.3K27M histone mutant (K27M)
#' as well as with or without treatment with EPZ6438 (EPZ), an inhibitor of the
#' catalytic reaction producing the H3K27me3 histone mark.
#'
#' @references
#' Mohammad F., Weissmann S., Leblanc B., Pandey D.P. et al.
#' EZH2 is a potential therapeutic target for H3K27M-mutant pediatric gliomas.
#' Nature Medicine 2017 \url{http://dx.doi.org/10.1038/nm.4293}
"NSC_K27M_COUNTS"

# =============================================================================.
#' H3K27me3 ChIP-seq in mouse Neuronal Stem Cell (NSCs) - METADATA
# -----------------------------------------------------------------------------.
#' @rdname NSC_K27M_COUNTS
#' @keywords internal
"NSC_K27M_METADATA"

# =============================================================================.
#' H3K27me3 ChIP-seq in mouse Neuronal Stem Cell (NSCs) - SPIKEIN
# -----------------------------------------------------------------------------.
#' @rdname NSC_K27M_COUNTS
#' @keywords internal
"NSC_K27M_SPIKEIN"
